[alembic]
script_location = migrations
sqlalchemy.url = postgresql://usuario:flexx123@localhost:5432/flexx_proposta
version_locations = %(here)s/versions
output_encoding = utf-8
file_template = %%(rev)s_%%(slug)s
truncate_slug_length = 40
revision_environment = false
revision_output_type = long
timezone = UTC
render_as_batch = false

[loggers]
keys = root, alembic, sqlalchemy

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[logger_sqlalchemy]
level = WARN
handlers = console
qualname = sqlalchemy

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S